"""ID allocation port."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from agent_evolve.domain.ids import (
    CandidateId,
    CorrelationId,
    EvaluationAttemptId,
    EvaluationId,
    EventId,
    GenerationId,
    InsightId,
    LLMCallId,
    OperatorInvocationId,
    ProviderAttemptId,
    RunId,
)


@runtime_checkable
class IdFactory(Protocol):
    def new_run_id(self) -> RunId: ...
    def new_event_id(self) -> EventId: ...
    def new_generation_id(self) -> GenerationId: ...
    def new_candidate_id(self) -> CandidateId: ...
    def new_insight_id(self) -> InsightId: ...
    def new_operator_invocation_id(self) -> OperatorInvocationId: ...
    def new_llm_call_id(self) -> LLMCallId: ...
    def new_provider_attempt_id(self) -> ProviderAttemptId: ...
    def new_evaluation_id(self) -> EvaluationId: ...
    def new_evaluation_attempt_id(self) -> EvaluationAttemptId: ...
    def new_correlation_id(self) -> CorrelationId: ...
