"""Framework-free domain types for durable AgentEvolve experiments."""

from agent_evolve.domain.artifact import ArtifactRef, ArtifactRole
from agent_evolve.domain.event import (
    ArtifactRegistered,
    CURRENT_EVENT_SCHEMA_VERSION,
    EventEnvelope,
    EventPayload,
    LLMRequestArtifactLinked,
    event_from_json,
    event_from_record,
    event_to_json,
    event_to_record,
    validated_event_snapshot,
    validate_event_value_schema,
    validate_inline_text_schema,
)
from agent_evolve.domain.inline_text import InlineTextPolicy, validate_inline_text
from agent_evolve.domain.finite_variation import (
    FiniteActionEvidenceBinding,
    FiniteVariationContract,
    FiniteVariationOption,
    bind_finite_action_evidence,
    validate_finite_variation_contract,
    validate_finite_variation_option,
)
from agent_evolve.domain.ids import (
    ArtifactId,
    CandidateId,
    CorrelationId,
    EvaluationAttemptId,
    EvaluationId,
    EventId,
    GenerationId,
    InsightId,
    LLMCallId,
    OperatorInvocationId,
    ProviderAttemptId,
    RunId,
    StableId,
)
from agent_evolve.domain.outcome import FailureCategory, FailureCode, FailureRecord
from agent_evolve.domain.variation_space import (
    AtomicEditOption,
    validate_atomic_edit_option,
)

__all__ = [
    "ArtifactId",
    "ArtifactRegistered",
    "ArtifactRef",
    "ArtifactRole",
    "AtomicEditOption",
    "CURRENT_EVENT_SCHEMA_VERSION",
    "CandidateId",
    "CorrelationId",
    "EvaluationAttemptId",
    "EvaluationId",
    "EventEnvelope",
    "EventId",
    "EventPayload",
    "FailureCategory",
    "FailureCode",
    "FailureRecord",
    "FiniteActionEvidenceBinding",
    "FiniteVariationContract",
    "FiniteVariationOption",
    "GenerationId",
    "InsightId",
    "InlineTextPolicy",
    "LLMCallId",
    "LLMRequestArtifactLinked",
    "OperatorInvocationId",
    "ProviderAttemptId",
    "RunId",
    "StableId",
    "bind_finite_action_evidence",
    "event_from_json",
    "event_from_record",
    "event_to_json",
    "event_to_record",
    "validated_event_snapshot",
    "validate_event_value_schema",
    "validate_finite_variation_contract",
    "validate_finite_variation_option",
    "validate_inline_text",
    "validate_inline_text_schema",
    "validate_atomic_edit_option",
]
